config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root "lists#index"

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:create]
  end

  resources :bookmarks, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list, message: 'This movie is already on your list' }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [list, bookmark] do |f| %>
  <div class="form-content">
    <%= f.input :movie_id, collection: Movie.all %>
    <%= f.input :comment %>
  </div>
  <%= f.button :submit, class: "form-btn" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="nav">
      <%= link_to "Lists", lists_path %>
      <h2>Watch List</h2>
      <%= link_to "Create a list", new_list_path %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for list do |f| %>
  <div class="form-content">
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
  </div>
  <%= f.button :submit, class: "form-btn" %>
<% end %>

app/views/lists/index.html.erb
<div class="container-index">
  <div class="cards">
    <h1>MovieLists</h1>
    <% @lists.each do |list| %>
      <% if list.photo.key %>
        <div class="card-list-with-img">
          <%= cl_image_tag list.photo.key, crop: :fill %>
          <div class="card-list-with-img-content">
            <p class="card-title"><%= list.name %></p>
            <p>A selection of films, just for you, to enjoy an amazing experience alone, with friends or family.</p>
            <p class="card-btn"><%= link_to "Ckeck this list", list_path(list) %></p>
          </div>
        </div>
      <% else %>
        <div class="card-list">
          <p class="card-title"><%= list.name %></p>
          <p>A selection of films, just for you, to enjoy an amazing experience alone, with friends or family.</p>
          <p class="card-btn"><%= link_to "Ckeck this list", list_path(list) %></p>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="card-image">
    <%= image_tag "poster.jpg", alt: "movie-poster", width: 500 %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>Create a new list</h1>

<%= render 'form', list:@list %>

app/views/lists/show.html.erb
<% if @list.photo.key %>
  <div class="container">
    <div class="card-image">
      <%= cl_image_tag @list.photo.key, crop: :fill %>
    </div>
    <div class="container-cards">
      <h1><%= @list.name %></h1>
      <div class="cards-show">
        <% @list.bookmarks.each do |bookmark| %>
          <div class="card-show">
            <div class="card-show-image">
              <%= image_tag bookmark.movie.poster_url, alt: "movie-poster", width: 200 %>
            </div>
            <div class="card-show-content">
              <p class="card-title"><%= bookmark.movie.title%></p>
              <p class="rating"><%= bookmark.movie.rating %>/5</p>
              <p><%= bookmark.movie.overview %></p>
              <p>My comment : <%= bookmark.comment %></p>
              <br>
              <p class="card-show-btn"><%= link_to "Delete this movie from my list", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <div class="container-cards">
    <h1><%= @list.name %></h1>
    <div class="cards-show">
      <% @list.bookmarks.each do |bookmark| %>
        <div class="card-show">
          <div class="card-show-image">
            <%= image_tag bookmark.movie.poster_url, alt: "movie-poster", width: 200 %>
          </div>
          <div class="card-show-content">
            <p class="card-title"><%= bookmark.movie.title%></p>
            <p class="rating"><%= bookmark.movie.rating %>/5</p>
            <p><%= bookmark.movie.overview %></p>
            <p>My comment : <%= bookmark.comment %></p>
            <br>
            <p class="card-show-btn"><%= link_to "Delete this movie from my list", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<div class="form">
  <h2>Add a movie to this list :</h2>
  <%= render 'bookmarks/form', list:@list, bookmark:@bookmark %>
</div>